### ISSUE TITLE
[REQUEST] feature:  Runway missing Ec2 node Tagging

### ISSUE THREAD

**Issue by shawnstout** [onicagroup/runway#486] opened 2020-11-14 22:27 UTC
**Is your feature request related to a problem? Please describe.**

Unable to Tag EC2 Instances from a EKS cluster that gets created through the Managed Node Group.  This makes it very hard to identify the cluster EC2 Instances.

**Describe the solution you'd like**
Add Tagging Capability that is already in Boto3.  Launch Template supports adding tags to EC2 Resources using TagSpecifications.  An example is below with the hyperlink to reference from Boto3 found in CreateLaunchTemplate.

https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2.html#EC2.Client.create_launch_template

'TagSpecifications': [
            {
                'ResourceType': 'instance',
                'Tags': [
                    {
                        'Key': 'Name',
                        'Value': 'ClusterName'
                    },
                ]
            },
        ],

When you use the syntax as above it errors out with ResourceType not found

**Comment by ITProKyle** [comment] 2020-11-14 23:50
Can you please provide more information for this feature request?

> Unable to Tag EC2 Instances from a EKS cluster that gets created through the Managed Node Group.

How what this infrastructure created? (e.g. Serverless, Terraform, CloudFormation template, CFNgin blueprint, etc)

Have you tried applying tags using methods supported natively by the IaC tool that Runway is orchestrating (e.g. Serverless, Terraform, Cloudformation, etc)?

> When you use the syntax as above it errors out with ResourceType not found

What produces the error? Are you using the latest version of Runway, boto3, and the IaC tool that Runway is orchestrating?
A deployment Runway is orchestrating is bound by what is supported by its dependencies. For example, if the error is coming from boto3 it's likely being caused by an outdated install of boto3.

**Comment by troyready** [comment] 2020-11-16 18:58
I'm going to close this for now as there's almost certainly nothing we can do here, as @ITProKyle described. We're happy to give more guidance if more info is provided on reproducing the error.

**Closed by troyready** 2020-11-16 18:58 UTC
Labels: feature, priority:low, status:review_needed

**Comment by shawnstout** [comment] 2020-11-16 21:12
How can you tag ec2 instances with names when NodeGroups are created now?  From what I can see tagging is missing from runway but the underlining aws nodegroup creation has the availability to do so.  I can provide more information if needed.  We are using your Professional Services with Onica on this engagement so please do not close this out @troyready

**Comment by shawnstout** [comment] 2020-11-16 21:25
> Can you please provide more information for this feature request?
> 
> > Unable to Tag EC2 Instances from a EKS cluster that gets created through the Managed Node Group.
> 
> How was this infrastructure created? (e.g. Serverless, Terraform, CloudFormation template, CFNgin blueprint, etc)
Infrastructure is created via aws cloudformation script which is created via python code and aws codepipeline.  The cloudformation script is created dynamically via runway and Kustomize.  
> 
> Have you tried applying tags using methods supported natively by the IaC tool that Runway is orchestrating (e.g. Serverless, Terraform, Cloudformation, etc)?
Everything is code driven via our github repo into codebuild.  a buildspec.yaml file is controlling this buildout.  A further explanation can be given from the Onica Professional Services team we have engaged.  Jonathan Best, Cory Twitty, Steve Lee and Steven Robineau are the developers who have created the solution for our company.  They would be able to provide better insight.
> 
> > When you use the syntax as above it errors out with ResourceType not found
Corret
> 
> What produces the error? Are you using the latest version of Runway, boto3, and the IaC tool that Runway is orchestrating?
> A deployment Runway is orchestrating is bound by what is supported by its dependencies. For example, if the error is coming from boto3 it's likely being caused by an outdated install of boto3.
the issue is that runway does not currently have the capability to tag the cluster nodes (ec2 instances) so you can identify them.
Versions we are currently using:  
requirements
boto3==1.14.55
nose==1.3.7
------------------------------------

**Comment by ITProKyle** [comment] 2020-11-16 22:32
> How can you tag ec2 instances with names when NodeGroups are created now?

From looking at the docs, it appears that tags would be applied in accordance with the launch template being used.

Setting the launch template: [AWS::EKS::Nodegroup.LaunchTemplateSpecification.Id](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-eks-nodegroup-launchtemplatespecification.html#cfn-eks-nodegroup-launchtemplatespecification-id)
Specifying tags in a launch template: [AWS::EC2::LaunchTemplate.LaunchTemplateData.TagSpecifications](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-launchtemplatedata.html#cfn-ec2-launchtemplate-launchtemplatedata-tagspecifications)

> From what I can see tagging is missing from runway

Runway itself is not responsible for applying tags to anything. It would be the responsibility of the IaC tool its orchestrating. Yes, CFNgin has a `tags` key but, propagation of the tags to resources is handled by CloudFormation and should not be relied on to cover _everything_.

---

Without having the exact error, this line leads me to believe the issue is Troposphere related.

> aws cloudformation script which is created via python code

Troposphere is a python library used to write/generate CloudFormation templates that we wrap via our CFNgin blueprints. I would suggest updating to the latest version to see if that solves the issue. Looking at their latest version, its not using any form of value validation on at field but an older version may ([source](https://github.com/cloudtools/troposphere/blob/2.6.3/troposphere/ec2.py#L1013)).

It could also be beneficial to update the version of boto3 as 1.14.55 is quite old. While your version does list support for the field/value you provided, it could be a bug in that version if boto3 is raising the error.

**Comment by shawnstout** [comment] 2020-11-16 22:50
Yes it seems that I need to add tags to troposphere, thanks

Shawn M. Stout
